from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Iterable

from flask import Flask, jsonify, render_template_string, request

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 10 * 1024 * 1024


FUNCTION_FLAGS: tuple[tuple[int, str], ...] = (
    (0x00000001, "Final"),
    (0x00000002, "RequiredAPI"),
    (0x00000004, "BlueprintAuthorityOnly"),
    (0x00000008, "BlueprintCosmetic"),
    (0x00000040, "Net"),
    (0x00000080, "NetReliable"),
    (0x00000100, "NetRequest"),
    (0x00000200, "Exec"),
    (0x00000400, "Native"),
    (0x00000800, "Event"),
    (0x00001000, "NetResponse"),
    (0x00002000, "Static"),
    (0x00004000, "NetMulticast"),
    (0x00008000, "UbergraphFunction"),
    (0x00010000, "MulticastDelegate"),
    (0x00020000, "Public"),
    (0x00040000, "Private"),
    (0x00080000, "Protected"),
    (0x00100000, "Delegate"),
    (0x00200000, "NetServer"),
    (0x00400000, "HasOutParms"),
    (0x00800000, "HasDefaults"),
    (0x01000000, "NetClient"),
    (0x02000000, "DLLImport"),
    (0x04000000, "BlueprintCallable"),
    (0x08000000, "BlueprintEvent"),
    (0x10000000, "BlueprintPure"),
    (0x20000000, "EditorOnly"),
    (0x40000000, "Const"),
    (0x80000000, "NetValidate"),
)

REFERENCE_PROPERTIES = (
    "FunctionReference",
    "VariableReference",
    "EventReference",
    "DelegateReference",
    "MacroGraphReference",
)

SEMANTIC_PROPERTIES = (
    "NodeComment",
    "EnabledState",
    "bIsPureFunc",
    "bIsConstFunc",
    "TargetType",
    "StructType",
    "Enum",
    "InputKey",
    "TimelineName",
    "ProxyFactoryFunctionName",
    "ProxyClass",
    "ClassToSpawn",
    "ComponentClass",
    "TemplateBlueprint",
)


@dataclass
class Pin:
    pin_id: str
    name: str
    direction: str
    category: str
    subcategory: str = ""
    subcategory_object: str = ""
    container: str = ""
    default: str = ""
    autogenerated_default: str = ""
    linked_to: list[tuple[str, str]] = field(default_factory=list)
    hidden: bool = False
    orphaned: bool = False
    is_reference: bool = False
    is_const: bool = False
    user_defined: bool = False


@dataclass
class Node:
    class_path: str
    name: str
    properties: dict[str, str] = field(default_factory=dict)
    pins: list[Pin] = field(default_factory=list)
    user_pin_names: set[str] = field(default_factory=set)

    @property
    def class_name(self) -> str:
        return self.class_path.rsplit(".", 1)[-1]

    @property
    def friendly_type(self) -> str:
        name = self.class_name
        return name.removeprefix("K2Node_")


def strip_quotes(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] == '"':
        return value[1:-1].replace(r'\"', '"')
    return value


def strip_outer_parentheses(value: str) -> str:
    value = value.strip()
    if value.startswith("(") and value.endswith(")"):
        return value[1:-1]
    return value


def split_top_level(text: str, delimiter: str = ",") -> list[str]:
    parts: list[str] = []
    start = 0
    depth = 0
    quote: str | None = None
    escaped = False

    for index, char in enumerate(text):
        if quote is not None:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            continue

        if char in ('"', "'"):
            quote = char
        elif char in "([{":
            depth += 1
        elif char in ")]}":
            depth = max(0, depth - 1)
        elif char == delimiter and depth == 0:
            parts.append(text[start:index].strip())
            start = index + 1

    tail = text[start:].strip()
    if tail:
        parts.append(tail)
    return parts


def parse_fields(text: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for item in split_top_level(strip_outer_parentheses(text)):
        if "=" not in item:
            continue
        key, value = item.split("=", 1)
        fields[key.strip()] = value.strip()
    return fields


def compact_reference(value: str) -> str:
    value = strip_quotes(value)
    if not value or value in {"None", "()"}:
        return value

    # Handles values such as:
    # /Script/Engine.BlueprintGeneratedClass'/Game/Foo/BP_Test.BP_Test_C'
    quoted_path = re.search(r"'([^']+)'", value)
    if quoted_path:
        value = quoted_path.group(1)

    value = value.rstrip("'")
    leaf = value.rsplit("/", 1)[-1]
    if "." in leaf:
        leaf = leaf.rsplit(".", 1)[-1]
    return leaf or value


def parse_bool(value: str) -> bool:
    return strip_quotes(value).lower() == "true"


def parse_links(value: str) -> list[tuple[str, str]]:
    return re.findall(r"([A-Za-z0-9_]+)\s+([A-Fa-f0-9]{32})", value)


def make_pin(fields: dict[str, str], *, user_defined: bool = False) -> Pin:
    pin_type_fields: dict[str, str] = {}
    if "PinType" in fields:
        pin_type_fields = parse_fields(fields["PinType"])

    def get(name: str, default: str = "") -> str:
        return fields.get(name, pin_type_fields.get(name, default))

    default_value = fields.get("DefaultValue", "")
    if not default_value:
        default_value = fields.get("DefaultObject", "") or fields.get("DefaultTextValue", "")

    return Pin(
        pin_id=strip_quotes(fields.get("PinId", "")),
        name=strip_quotes(fields.get("PinName", "<unnamed>")),
        direction="out" if strip_quotes(get("Direction", fields.get("DesiredPinDirection", ""))) == "EGPD_Output" else "in",
        category=strip_quotes(get("PinType.PinCategory", get("PinCategory", "unknown"))),
        subcategory=strip_quotes(get("PinType.PinSubCategory", get("PinSubCategory", ""))),
        subcategory_object=get("PinType.PinSubCategoryObject", get("PinSubCategoryObject", "")),
        container=strip_quotes(get("PinType.ContainerType", get("ContainerType", ""))),
        default=strip_quotes(default_value),
        autogenerated_default=strip_quotes(fields.get("AutogeneratedDefaultValue", "")),
        linked_to=parse_links(fields.get("LinkedTo", "")),
        hidden=parse_bool(fields.get("bHidden", "False")),
        orphaned=parse_bool(fields.get("bOrphanedPin", "False")),
        is_reference=parse_bool(get("PinType.bIsReference", get("bIsReference", "False"))),
        is_const=parse_bool(get("PinType.bIsConst", get("bIsConst", "False"))),
        user_defined=user_defined,
    )


def parse_blueprint(text: str) -> list[Node]:
    nodes: list[Node] = []
    current: Node | None = None

    for raw_line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        line = raw_line.strip()
        if not line:
            continue

        if line.startswith("Begin Object "):
            class_match = re.search(r"\bClass=([^\s]+)", line)
            name_match = re.search(r'\bName="([^"]+)"', line)
            if not class_match or not name_match:
                continue
            current = Node(class_path=class_match.group(1), name=name_match.group(1))
            continue

        if line == "End Object":
            if current is not None:
                # Apply UserDefinedPin information to matching serialized pins.
                for pin in current.pins:
                    if pin.name in current.user_pin_names:
                        pin.user_defined = True
                nodes.append(current)
            current = None
            continue

        if current is None:
            continue

        if line.startswith("CustomProperties Pin ("):
            inner = line[line.find("(") :]
            current.pins.append(make_pin(parse_fields(inner)))
            continue

        if line.startswith("CustomProperties UserDefinedPin ("):
            inner = line[line.find("(") :]
            fields = parse_fields(inner)
            user_pin = make_pin(fields, user_defined=True)
            current.user_pin_names.add(user_pin.name)
            # A normal Pin entry usually exists too. Add a synthetic pin only if it does not.
            if not any(pin.name == user_pin.name for pin in current.pins):
                current.pins.append(user_pin)
            continue

        if "=" in line:
            key, value = line.split("=", 1)
            current.properties[key.strip()] = value.strip()

    # Recover a final object if malformed clipboard text omitted End Object.
    if current is not None:
        nodes.append(current)

    return nodes


def decode_function_flags(raw_value: str, *, compact: bool) -> list[str]:
    try:
        value = int(strip_quotes(raw_value), 0)
    except (TypeError, ValueError):
        return [strip_quotes(raw_value)]

    names = [name for bit, name in FUNCTION_FLAGS if value & bit]
    if compact:
        names = [name for name in names if name not in {"HasOutParms", "HasDefaults"}]
    known_mask = 0
    for bit, _ in FUNCTION_FLAGS:
        known_mask |= bit
    unknown = value & ~known_mask
    if unknown:
        names.append(f"UnknownFlags({unknown:#x})")
    return names or ["None"]


def pin_type(pin: Pin) -> str:
    category = pin.category or "unknown"
    subtype = pin.subcategory
    object_name = compact_reference(pin.subcategory_object)

    if category == "real" and subtype:
        result = subtype
    elif category == "struct" and object_name:
        result = object_name
    elif category in {"object", "class", "softobject", "softclass", "interface"}:
        result = f"{category}<{object_name}>" if object_name else category
    elif category == "byte" and object_name:
        result = f"enum<{object_name}>"
    else:
        result = category
        if subtype and subtype not in {"None", category}:
            result += f"<{subtype}>"

    container = pin.container
    if container and container != "None":
        normalized = {
            "Array": "array",
            "Set": "set",
            "Map": "map",
        }.get(container, container.lower())
        result = f"{normalized}<{result}>"

    if pin.is_const:
        result = f"const {result}"
    if pin.is_reference:
        result += "&"
    return result


def meaningful_default(pin: Pin) -> str:
    value = pin.default
    if not value or value == pin.autogenerated_default:
        return ""
    return compact_reference(value) if ("/Script/" in value or "'/Game/" in value) else value


def include_pin(pin: Pin, mode: str) -> bool:
    if pin.orphaned and not pin.linked_to:
        return False
    if pin.linked_to or pin.user_defined:
        return True
    if mode == "conservative":
        return not pin.hidden
    if pin.direction == "in" and meaningful_default(pin):
        return True
    return False


def reference_details(raw_value: str) -> dict[str, str]:
    fields = parse_fields(raw_value)
    details: dict[str, str] = {}
    for source, target in (
        ("MemberName", "member"),
        ("MemberParent", "owner"),
        ("MemberScope", "scope"),
        ("bSelfContext", "self_context"),
    ):
        if source not in fields:
            continue
        value = strip_quotes(fields[source])
        if source == "MemberParent":
            value = compact_reference(value)
        details[target] = value
    return details


def node_title(node: Node) -> str:
    if "CustomFunctionName" in node.properties:
        return strip_quotes(node.properties["CustomFunctionName"])

    for key in REFERENCE_PROPERTIES:
        raw = node.properties.get(key)
        if raw:
            member = reference_details(raw).get("member")
            if member:
                return member

    for key in ("TimelineName", "ProxyFactoryFunctionName", "InputKey"):
        if key in node.properties:
            return strip_quotes(node.properties[key])

    return ""


def node_metadata(node: Node, *, compact: bool) -> list[str]:
    metadata: list[str] = []

    flags = node.properties.get("FunctionFlags")
    if flags:
        decoded = decode_function_flags(flags, compact=compact)
        if compact and "Net" in decoded:
            rpc_kind = next(
                (name for name in ("NetServer", "NetClient", "NetMulticast") if name in decoded),
                "Network",
            )
            reliability = "Reliable" if "NetReliable" in decoded else "Unreliable"
            display_kind = {
                "NetServer": "Server",
                "NetClient": "Client",
                "NetMulticast": "NetMulticast",
            }.get(rpc_kind, rpc_kind)
            metadata.append(f"rpc: {display_kind}, {reliability}")
            decoded = [
                name
                for name in decoded
                if name not in {"Net", "NetReliable", "NetServer", "NetClient", "NetMulticast"}
            ]
        if decoded:
            metadata.append("flags: " + ", ".join(decoded))

    for key in REFERENCE_PROPERTIES:
        raw = node.properties.get(key)
        if not raw:
            continue
        details = reference_details(raw)
        owner = details.get("owner")
        scope = details.get("scope")
        self_context = details.get("self_context")
        if owner:
            metadata.append(f"owner: {owner}")
        if scope:
            metadata.append(f"scope: {scope}")
        if self_context:
            if self_context.lower() == "true":
                metadata.append("target: self")
            else:
                metadata.append("self_context: false")
        break

    for key in SEMANTIC_PROPERTIES:
        if key not in node.properties:
            continue
        raw = strip_quotes(node.properties[key])
        if not raw or raw in {"None", "()"}:
            continue
        value = compact_reference(raw) if ("/Script/" in raw or "'/Game/" in raw) else raw
        metadata.append(f"{key}: {value}")

    return metadata


def build_connections(nodes: Iterable[Node]) -> list[str]:
    node_list = list(nodes)
    pin_index: dict[tuple[str, str], Pin] = {}
    for node in node_list:
        for pin in node.pins:
            if pin.pin_id:
                pin_index[(node.name, pin.pin_id)] = pin

    connections: list[str] = []
    seen: set[tuple[str, str, str, str, str]] = set()

    for node in node_list:
        for pin in node.pins:
            for other_node_name, other_pin_id in pin.linked_to:
                other_pin = pin_index.get((other_node_name, other_pin_id))
                other_pin_name = other_pin.name if other_pin else f"<pin:{other_pin_id[:8]}>"

                if pin.direction == "out":
                    edge = (node.name, pin.name, other_node_name, other_pin_name, "->")
                elif other_pin is not None and other_pin.direction == "out":
                    edge = (other_node_name, other_pin_name, node.name, pin.name, "->")
                else:
                    # Direction cannot be resolved when the linked node was not copied.
                    edge = (node.name, pin.name, other_node_name, other_pin_name, "--")

                if edge in seen:
                    continue
                seen.add(edge)
                left_node, left_pin, right_node, right_pin, arrow = edge
                connections.append(f"{left_node}.{left_pin} {arrow} {right_node}.{right_pin}")

    return connections


def debloat_blueprint(text: str, mode: str = "compact") -> str:
    mode = "conservative" if mode == "conservative" else "compact"
    nodes = parse_blueprint(text)
    if not nodes:
        raise ValueError("No 'Begin Object ... End Object' Blueprint nodes were found.")

    compact = mode == "compact"
    lines = [
        "BLUEPRINT GRAPH",
        f"nodes: {len(nodes)}",
        f"mode: {mode}",
        "",
        "NODES",
    ]

    for node in nodes:
        title = node_title(node)
        header = f"{node.name}: {node.friendly_type}"
        if title:
            header += f' "{title}"'
        lines.append(header)

        for item in node_metadata(node, compact=compact):
            lines.append(f"  {item}")

        selected_pins = [pin for pin in node.pins if include_pin(pin, mode)]
        input_pins = [pin for pin in selected_pins if pin.direction == "in"]
        output_pins = [pin for pin in selected_pins if pin.direction == "out"]

        def format_pins(pins: list[Pin]) -> str:
            formatted: list[str] = []
            for pin in pins:
                item = f"{pin.name}:{pin_type(pin)}"
                default = meaningful_default(pin)
                if default:
                    item += f"={default}"
                formatted.append(item)
            return ", ".join(formatted)

        if input_pins:
            lines.append(f"  inputs: {format_pins(input_pins)}")
        if output_pins:
            lines.append(f"  outputs: {format_pins(output_pins)}")

    connections = build_connections(nodes)
    if connections:
        lines.extend(("", "CONNECTIONS"))
        lines.extend(connections)

    return "\n".join(lines).strip() + "\n"


HTML = r"""
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>UE Blueprint Debloater</title>
  <style>
    :root {
      color-scheme: dark;
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #111318;
      color: #e8eaf0;
    }
    * { box-sizing: border-box; }
    body { margin: 0; min-height: 100vh; background: #111318; }
    main { width: min(1500px, 96vw); margin: 24px auto; }
    h1 { margin: 0 0 6px; font-size: 1.55rem; }
    .subtitle { margin: 0 0 18px; color: #aeb5c4; }
    .toolbar { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; margin-bottom: 12px; }
    button, select {
      border: 1px solid #394150;
      border-radius: 8px;
      background: #202632;
      color: #f3f5f8;
      padding: 9px 13px;
      font: inherit;
    }
    button { cursor: pointer; }
    button:hover { background: #2a3240; }
    button.primary { background: #4263eb; border-color: #5672ee; }
    button.primary:hover { background: #4c6ef5; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }
    .panel { min-width: 0; }
    label { display: block; margin-bottom: 7px; font-weight: 650; }
    textarea {
      width: 100%;
      min-height: 68vh;
      resize: vertical;
      border: 1px solid #303847;
      border-radius: 10px;
      background: #171b23;
      color: #e8eaf0;
      padding: 14px;
      font: 13px/1.48 "Cascadia Code", "JetBrains Mono", Consolas, monospace;
      tab-size: 2;
    }
    textarea:focus { outline: 2px solid #4263eb; border-color: transparent; }
    .stats { margin-left: auto; color: #aeb5c4; font-size: 0.92rem; }
    .error { min-height: 1.2em; margin-top: 10px; color: #ff8787; }
    @media (max-width: 900px) {
      .grid { grid-template-columns: 1fr; }
      textarea { min-height: 42vh; }
      .stats { width: 100%; margin-left: 0; }
    }
  </style>
</head>
<body>
<main>
  <h1>UE Blueprint Debloater</h1>
  <p class="subtitle">Paste copied Blueprint nodes, keep graph semantics, remove editor serialization noise.</p>

  <div class="toolbar">
    <select id="mode" aria-label="Debloat mode">
      <option value="compact" selected>Compact</option>
      <option value="conservative">Conservative</option>
    </select>
    <button class="primary" id="debloat">Debloat</button>
    <button id="copy">Copy output</button>
    <button id="clear">Clear</button>
    <span class="stats" id="stats"></span>
  </div>

  <div class="grid">
    <section class="panel">
      <label for="input">Blueprint clipboard text</label>
      <textarea id="input" spellcheck="false" placeholder="Begin Object Class=/Script/BlueprintGraph..."></textarea>
    </section>
    <section class="panel">
      <label for="output">LLM-ready text</label>
      <textarea id="output" spellcheck="false" readonly></textarea>
    </section>
  </div>
  <div class="error" id="error"></div>
</main>
<script>
  const input = document.getElementById("input");
  const output = document.getElementById("output");
  const stats = document.getElementById("stats");
  const errorBox = document.getElementById("error");
  const mode = document.getElementById("mode");

  async function debloat() {
    errorBox.textContent = "";
    stats.textContent = "Processing…";
    try {
      const response = await fetch("/api/debloat", {
        method: "POST",
        headers: {"Content-Type": "application/json"},
        body: JSON.stringify({text: input.value, mode: mode.value})
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Unable to process Blueprint text.");
      output.value = data.result;
      stats.textContent = `${data.input_chars.toLocaleString()} → ${data.output_chars.toLocaleString()} chars (${data.reduction_percent}% smaller)`;
    } catch (error) {
      errorBox.textContent = error.message;
      stats.textContent = "";
    }
  }

  document.getElementById("debloat").addEventListener("click", debloat);
  document.getElementById("copy").addEventListener("click", async () => {
    if (!output.value) return;
    await navigator.clipboard.writeText(output.value);
    stats.textContent = "Output copied.";
  });
  document.getElementById("clear").addEventListener("click", () => {
    input.value = "";
    output.value = "";
    stats.textContent = "";
    errorBox.textContent = "";
    input.focus();
  });

  input.addEventListener("keydown", (event) => {
    if ((event.ctrlKey || event.metaKey) && event.key === "Enter") debloat();
  });
</script>
</body>
</html>
"""


@app.get("/")
def index():
    return render_template_string(HTML)


@app.post("/api/debloat")
def api_debloat():
    payload = request.get_json(silent=True) or {}
    text = payload.get("text", "")
    mode = payload.get("mode", "compact")

    if not isinstance(text, str) or not text.strip():
        return jsonify(error="Paste copied Blueprint text first."), 400

    try:
        result = debloat_blueprint(text, mode)
    except ValueError as exc:
        return jsonify(error=str(exc)), 400

    input_chars = len(text)
    output_chars = len(result)
    reduction = round((1 - output_chars / max(input_chars, 1)) * 100, 1)
    return jsonify(
        result=result,
        input_chars=input_chars,
        output_chars=output_chars,
        reduction_percent=reduction,
    )


if __name__ == "__main__":
    print("UE Blueprint Debloater: http://127.0.0.1:5000")
    app.run(host="127.0.0.1", port=5000, debug=False)
